// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: testpb/book.proto

package testpbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	testpb "github.com/hxtk/aip/internal/testpb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BookServiceName is the fully-qualified name of the BookService service.
	BookServiceName = "test.BookService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BookServiceGetBookProcedure is the fully-qualified name of the BookService's GetBook RPC.
	BookServiceGetBookProcedure = "/test.BookService/GetBook"
	// BookServiceListBooksProcedure is the fully-qualified name of the BookService's ListBooks RPC.
	BookServiceListBooksProcedure = "/test.BookService/ListBooks"
)

// BookServiceClient is a client for the test.BookService service.
type BookServiceClient interface {
	GetBook(context.Context, *connect.Request[testpb.GetBookRequest]) (*connect.Response[testpb.Book], error)
	ListBooks(context.Context, *connect.Request[testpb.ListBooksRequest]) (*connect.ServerStreamForClient[testpb.Book], error)
}

// NewBookServiceClient constructs a client for the test.BookService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBookServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BookServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	bookServiceMethods := testpb.File_testpb_book_proto.Services().ByName("BookService").Methods()
	return &bookServiceClient{
		getBook: connect.NewClient[testpb.GetBookRequest, testpb.Book](
			httpClient,
			baseURL+BookServiceGetBookProcedure,
			connect.WithSchema(bookServiceMethods.ByName("GetBook")),
			connect.WithClientOptions(opts...),
		),
		listBooks: connect.NewClient[testpb.ListBooksRequest, testpb.Book](
			httpClient,
			baseURL+BookServiceListBooksProcedure,
			connect.WithSchema(bookServiceMethods.ByName("ListBooks")),
			connect.WithClientOptions(opts...),
		),
	}
}

// bookServiceClient implements BookServiceClient.
type bookServiceClient struct {
	getBook   *connect.Client[testpb.GetBookRequest, testpb.Book]
	listBooks *connect.Client[testpb.ListBooksRequest, testpb.Book]
}

// GetBook calls test.BookService.GetBook.
func (c *bookServiceClient) GetBook(ctx context.Context, req *connect.Request[testpb.GetBookRequest]) (*connect.Response[testpb.Book], error) {
	return c.getBook.CallUnary(ctx, req)
}

// ListBooks calls test.BookService.ListBooks.
func (c *bookServiceClient) ListBooks(ctx context.Context, req *connect.Request[testpb.ListBooksRequest]) (*connect.ServerStreamForClient[testpb.Book], error) {
	return c.listBooks.CallServerStream(ctx, req)
}

// BookServiceHandler is an implementation of the test.BookService service.
type BookServiceHandler interface {
	GetBook(context.Context, *connect.Request[testpb.GetBookRequest]) (*connect.Response[testpb.Book], error)
	ListBooks(context.Context, *connect.Request[testpb.ListBooksRequest], *connect.ServerStream[testpb.Book]) error
}

// NewBookServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBookServiceHandler(svc BookServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	bookServiceMethods := testpb.File_testpb_book_proto.Services().ByName("BookService").Methods()
	bookServiceGetBookHandler := connect.NewUnaryHandler(
		BookServiceGetBookProcedure,
		svc.GetBook,
		connect.WithSchema(bookServiceMethods.ByName("GetBook")),
		connect.WithHandlerOptions(opts...),
	)
	bookServiceListBooksHandler := connect.NewServerStreamHandler(
		BookServiceListBooksProcedure,
		svc.ListBooks,
		connect.WithSchema(bookServiceMethods.ByName("ListBooks")),
		connect.WithHandlerOptions(opts...),
	)
	return "/test.BookService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BookServiceGetBookProcedure:
			bookServiceGetBookHandler.ServeHTTP(w, r)
		case BookServiceListBooksProcedure:
			bookServiceListBooksHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBookServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBookServiceHandler struct{}

func (UnimplementedBookServiceHandler) GetBook(context.Context, *connect.Request[testpb.GetBookRequest]) (*connect.Response[testpb.Book], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("test.BookService.GetBook is not implemented"))
}

func (UnimplementedBookServiceHandler) ListBooks(context.Context, *connect.Request[testpb.ListBooksRequest], *connect.ServerStream[testpb.Book]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("test.BookService.ListBooks is not implemented"))
}
