// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: testpb/book.proto

package testpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Author struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GivenName     string                 `protobuf:"bytes,1,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	FamilyName    string                 `protobuf:"bytes,2,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Author) Reset() {
	*x = Author{}
	mi := &file_testpb_book_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Author) ProtoMessage() {}

func (x *Author) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_book_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Author.ProtoReflect.Descriptor instead.
func (*Author) Descriptor() ([]byte, []int) {
	return file_testpb_book_proto_rawDescGZIP(), []int{0}
}

func (x *Author) GetGivenName() string {
	if x != nil {
		return x.GivenName
	}
	return ""
}

func (x *Author) GetFamilyName() string {
	if x != nil {
		return x.FamilyName
	}
	return ""
}

type Book struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Title   string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Author  *Author                `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Authors []*Author              `protobuf:"bytes,3,rep,name=authors,proto3" json:"authors,omitempty"`
	// Simple string map
	Reviews map[string]string `protobuf:"bytes,4,rep,name=reviews,proto3" json:"reviews,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Int-keyed map
	Items map[int32]string `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Example output-only field
	Name          string `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_testpb_book_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_book_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_testpb_book_proto_rawDescGZIP(), []int{1}
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *Book) GetAuthors() []*Author {
	if x != nil {
		return x.Authors
	}
	return nil
}

func (x *Book) GetReviews() map[string]string {
	if x != nil {
		return x.Reviews
	}
	return nil
}

func (x *Book) GetItems() map[int32]string {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Book) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_testpb_book_proto protoreflect.FileDescriptor

const file_testpb_book_proto_rawDesc = "" +
	"\n" +
	"\x11testpb/book.proto\x12\x04test\"H\n" +
	"\x06Author\x12\x1d\n" +
	"\n" +
	"given_name\x18\x01 \x01(\tR\tgivenName\x12\x1f\n" +
	"\vfamily_name\x18\x02 \x01(\tR\n" +
	"familyName\"\xd4\x02\n" +
	"\x04Book\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12$\n" +
	"\x06author\x18\x02 \x01(\v2\f.test.AuthorR\x06author\x12&\n" +
	"\aauthors\x18\x03 \x03(\v2\f.test.AuthorR\aauthors\x121\n" +
	"\areviews\x18\x04 \x03(\v2\x17.test.Book.ReviewsEntryR\areviews\x12+\n" +
	"\x05items\x18\x05 \x03(\v2\x15.test.Book.ItemsEntryR\x05items\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x1a:\n" +
	"\fReviewsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01Bp\n" +
	"\bcom.testB\tBookProtoP\x01Z)github.com/hxtk/aip/masks/internal/testpb\xa2\x02\x03TXX\xaa\x02\x04Test\xca\x02\x04Test\xe2\x02\x10Test\\GPBMetadata\xea\x02\x04Testb\x06proto3"

var (
	file_testpb_book_proto_rawDescOnce sync.Once
	file_testpb_book_proto_rawDescData []byte
)

func file_testpb_book_proto_rawDescGZIP() []byte {
	file_testpb_book_proto_rawDescOnce.Do(func() {
		file_testpb_book_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testpb_book_proto_rawDesc), len(file_testpb_book_proto_rawDesc)))
	})
	return file_testpb_book_proto_rawDescData
}

var file_testpb_book_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_testpb_book_proto_goTypes = []any{
	(*Author)(nil), // 0: test.Author
	(*Book)(nil),   // 1: test.Book
	nil,            // 2: test.Book.ReviewsEntry
	nil,            // 3: test.Book.ItemsEntry
}
var file_testpb_book_proto_depIdxs = []int32{
	0, // 0: test.Book.author:type_name -> test.Author
	0, // 1: test.Book.authors:type_name -> test.Author
	2, // 2: test.Book.reviews:type_name -> test.Book.ReviewsEntry
	3, // 3: test.Book.items:type_name -> test.Book.ItemsEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_testpb_book_proto_init() }
func file_testpb_book_proto_init() {
	if File_testpb_book_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testpb_book_proto_rawDesc), len(file_testpb_book_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testpb_book_proto_goTypes,
		DependencyIndexes: file_testpb_book_proto_depIdxs,
		MessageInfos:      file_testpb_book_proto_msgTypes,
	}.Build()
	File_testpb_book_proto = out.File
	file_testpb_book_proto_goTypes = nil
	file_testpb_book_proto_depIdxs = nil
}
